GET http://localhost:8000/user/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

###

POST http://localhost:8000/user/login
Content-Type: application/json

{
    "password": "acroknacks",
    "phone": "9012388924"
}


###

POST http://localhost:8000/user
Content-Type: application/json

{
    "name": "User3",
    "phone": "9012388926",
    "password": "acroknacks"
}

###

DELETE http://localhost:8000/user/6537bc74970cd873f8320da8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

###

GET http://localhost:8000/group/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

###

GET http://localhost:8000/group/get/653a28e721540cff1ce8ae5d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

###

POST http://localhost:8000/group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

{
    "name": "Group2"
}

###

PATCH http://localhost:8000/group/addMember
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

{
    "memberId": "653a2581724fe6f9ca46f137",
    "groupId": "653a28e721540cff1ce8ae5d"
}


###

GET http://localhost:8000/group/mygroups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA


###

PATCH http://localhost:8000/group/member/653a21c38faa99623d59bfa6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

{
    "userId": "65376f6b6fd89909876f1be9"
}

###

PATCH http://localhost:8000/group/65377f9b31a45eb4e53ffefa/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

{
    "userId": "65376f6b6fd89909876f1be9",
    "message": "Hello this is sample message"
}

###

DELETE http://localhost:8000/group/653a22f27b6395517918a7e8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA

###

DELETE http://localhost:8000/group/653a28e721540cff1ce8ae5d/member/653a2576724fe6f9ca46f135
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyMDcwYWVjYWJkMDY3OGNlNWZjZSIsImlhdCI6MTY5ODMwODIxNywiZXhwIjoxNjk5MTcyMjE3fQ.fahylwtK4uUp0xypxtyzGfTVARqD-wFBTA-uX9XvXSA
