GET http://localhost:8000/user/all
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

###

POST http://localhost:8000/user/login
Content-Type: application/json

{
    "password": "acroknacks",
    "phone": "9012388924"
}


###

POST http://localhost:8000/user
Content-Type: application/json

{
    "name": "User3",
    "phone": "9012388926",
    "password": "acroknacks"
}

###

DELETE http://localhost:8000/user/6537bc74970cd873f8320da8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

###

GET http://localhost:8000/group/653a28e721540cff1ce8ae5d/nonparticipents
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM


###

GET http://localhost:8000/group/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

###

GET http://localhost:8000/group/get/653a28e721540cff1ce8ae5d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

###

POST http://localhost:8000/group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

{
    "name": "Group2"
}

###

PATCH http://localhost:8000/group/addMember
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

{
    "memberId": "653a2581724fe6f9ca46f137",
    "groupId": "653a28e721540cff1ce8ae5d"
}


###

GET http://localhost:8000/group/mygroups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM


###

PATCH http://localhost:8000/group/member/653a21c38faa99623d59bfa6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

{
    "userId": "65376f6b6fd89909876f1be9"
}

###

PATCH http://localhost:8000/group/653a807ed2f7d8de8724614c/chat
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

{
    "message": "Hello this is sample message111"
}

###


DELETE http://localhost:8000/group/653a807ed2f7d8de8724614c/chat/653a4114b255652e57553407
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM


###

DELETE http://localhost:8000/group/653a7f51904c2d4a15c23da7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM

###

DELETE http://localhost:8000/group/653a28e721540cff1ce8ae5d/member/653a2576724fe6f9ca46f135
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1M2EyNTc2NzI0ZmU2ZjljYTQ2ZjEzNSIsImlhdCI6MTY5ODQwNDM5NCwiZXhwIjoxNjk5MjY4Mzk0fQ.Km7hZIitJyg96GRPz8M2k30HBYKkF62BrZoDZkyJQaM
